#trufflehog yaml
#repos:
#- repo: local
 # hooks:
  #   id: Trufflehog
   #  name: TruffleHog
    # description: Detect secrets in your data.
     #entry: bash -c 'trufflehog-launcher git main HEAD'
     #entry: ./trufflehog_check.sh
     #language: system
     #stages: ["commit", "push"]
     #pass_filenames: false

# .gitleaks.toml


#gitleaks yaml

repos:
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.15.2  # Update to the latest release tag
    hooks:
    -   id: gitleaks
        args: ["detect", "--source", ".", "--report-path", "gitleaks-reports.json", "--verbose"]
